version: "3.9"
services:
  blazorapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
      POSTGRES_DB: appdb
    command: -p 8752
    ports:
      - "8752:8752"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
